# Generated by Django 5.1.1 on 2024-10-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organization_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
