# Generated by Django 5.1.1 on 2025-01-16 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('template', models.JSONField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('removed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-updated_on'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('removed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('removed', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('latitude', 'longitude')},
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField()),
                ('removed', models.BooleanField(default=False)),
                ('annotator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotations', to='annotation.annotationform')),
                ('coordinates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='annotation.coordinates')),
            ],
            options={
                'ordering': ['-updated_on'],
            },
        ),
        migrations.CreateModel(
            name='AnnotationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_images', to='annotation.annotation')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_image', to='annotation.file')),
            ],
        ),
        migrations.CreateModel(
            name='Sidewalk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessibility_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('adjacent_street', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.JSONField()),
                ('results', models.JSONField(blank=True, null=True)),
                ('anchor', models.CharField(choices=[('123.9419001850121,10.327600060884297', 'Anchor A'), ('123.94220321636607,10.328668797875494', 'Anchor B'), ('123.94318663887299,10.327099440742616', 'Anchor C'), ('123.94351254051777,10.328185054214456', 'Anchor D'), ('123.94495908641485,10.32757193618587', 'Anchor E'), ('123.94445022244315,10.326536945241577', 'Anchor F')], default='123.94318663887299,10.327099440742616', max_length=50)),
                ('removed', models.BooleanField(default=False)),
                ('end_coordinates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_sidewalk', to='annotation.coordinates')),
                ('start_coordinates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_sidewalk', to='annotation.coordinates')),
            ],
            options={
                'unique_together': {('start_coordinates', 'end_coordinates')},
            },
        ),
        migrations.AddField(
            model_name='annotation',
            name='sidewalk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='annotation.sidewalk'),
        ),
    ]
