# Generated by Django 5.1.1 on 2024-10-17 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('removed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('removed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='removed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('form_data', models.JSONField()),
                ('removed', models.BooleanField(default=False)),
                ('annotator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_annotations', to=settings.AUTH_USER_MODEL)),
                ('form_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_annotations', to='annotation.annotationform')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='annotation.location')),
            ],
        ),
        migrations.CreateModel(
            name='AnnotationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='annotation.annotation')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_annotations', to='annotation.file')),
            ],
        ),
    ]
