# Generated by Django 5.1.1 on 2024-10-17 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0002_annotationform_location_file_removed_annotation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annotation',
            options={'ordering': ['-updated_on']},
        ),
        migrations.AlterModelOptions(
            name='annotationform',
            options={'ordering': ['-updated_on']},
        ),
    ]
