# Generated by Django 5.1.1 on 2024-10-19 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0004_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinates',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
