# Generated by Django 5.1.1 on 2024-10-19 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0005_coordinates_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='coordinates',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coordinates_annotations', to='annotation.coordinates'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='end_coordinates',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='end_location', to='annotation.coordinates'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='start_coordinates',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='start_location', to='annotation.coordinates'),
            preserve_default=False,
        ),
    ]
