# Generated by Django 5.1.1 on 2024-10-19 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0006_annotation_coordinates_location_end_coordinates_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotationform',
            old_name='data',
            new_name='form_data',
        ),
        migrations.AddField(
            model_name='annotationform',
            name='name',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
    ]
