# Generated by Django 5.1.1 on 2024-10-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0007_rename_data_annotationform_form_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='accessibility_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='adjacent_street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
